name: deploy
on:
  push:
    branches: [ "main" ]
jobs:
  ssh-connectivity-check:
    runs-on: ubuntu-latest
    steps:
      - name: whoami
        uses: appleboy/ssh-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          script: |
            whoami
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: >
          npm --prefix server run test
  deploy:
    concurrency: ssh-deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: >
          npm --prefix client ci
      - run: >
          npm --prefix client run build
      - run: >
          npm --prefix server ci --os=linux --cpu=arm64
      - name: stop service
        uses: appleboy/ssh-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          script: |
            sudo systemctl stop chicken-coop
            rm -rf /app/*
      - name: copy client build
        uses: appleboy/scp-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          source: "client/build/*"
          target: "/app/"
      - name: copy server
        uses: appleboy/scp-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          source: "server/*"
          target: "/app"
      - name: copy service def
        uses: appleboy/scp-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          source: "chicken-coop.service"
          target: "/app/"
      - name: start service
        uses: appleboy/ssh-action@v1
        with:
          host: chicken-coop
          username: sullage
          key: ${{ secrets.COOP_KEY }}
          proxy_host: glowbox.pessimistic-it.com
          proxy_username: sullage
          proxy_key: ${{ secrets.PROXY_KEY }}
          script: |
            sudo cp -f /app/chicken-coop.service /lib/systemd/system/chicken-coop.service
            sudo systemctl daemon-reload
            sudo systemctl start chicken-coop
